version: '3.8'
services:
  timecard_bot:
    build: ./ #Dockerfileがあるディレクトリを指定
    volumes:
      - ./bot:/usr/src/app #botディレクトリをボリュームとして/usr/src/appにマウント
    environment:
      - TOKEN=${TOKEN}
      - SEND_CHANNEL=${SEND_CHANNEL}
      - MY_GUILD=${MY_GUILD}
    tty: true #ポート待受していない場合コンテナが終了するのを防ぐ